export const SET_HEIGHT = 'grid/SET_HEIGHT'
export const SET_WIDTH = 'grid/SET_WIDTH'
export const SET_NUM_IN_PATTERN = 'grid/SET_NUM_IN_PATTERN'
export const SET_TILES = 'grid/SET_TILES'
export const SET_SHOW_FILL_HELP = 'grid/SET_SHOW_FILL_HELP'
export const SET_SHOW_COLOR_HELP = 'grid/SET_SHOW_COLOR_HELP'
export const SET_REVEAL = 'grid/SET_REVEAL'
export const SET_TIME = 'grid/SET_TIME'
export const RESET_TILES = 'grid/RESET_TILES'

export const SET_COLOR = 'grid-tile/SET_COLOR'
export const SET_FILLED = 'grid-tile/SET_FILLED'
export const TOGGLE_FILLED = 'grid-tile/TOGGLE_FILLED'
export const SET_FILLED_STATUS = 'grid-tile/SET_FILLED_STATUS'
export const SET_PATTERN_FILLED = 'grid-tile/SET_PATTERN_FILLED'
export const SET_PATTERN_COLOR = 'grid-tile/SET_PATTERN_COLOR'